# docker-compose.override.yml
services:
  frontend:
    build:
      context: ./Memo
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./Memo:/app
      - /app/node_modules
    depends_on:
      - backend1
    networks:
      - appnet

  backend1:
    build:
      context: ./Express
    env_file:
      - ./Express/.env
    ports:
      - "8000:8000"
    volumes:
      - ./Express:/app
      - /app/node_modules
    networks:
      - appnet

volumes:
  shared-data:

networks:
  appnet:
    driver: bridge


